--we will create a database called Phonepay_Project

create database Phonepay_Project

use Phonepe_Project
go

--we will import the CSV File for analysis the data
--after importing the data

select * from phonepe

--Q1. Count The Total Transactions


select * from phonepe

select count(Transaction_id) as total_Transactions
from phonepe

---------------------------------------------------------------------------------------------------

--Q2. Total Transactions Amount


select * from phonepe

select round(sum(amount),2) as total_Revenue
from phonepe

---------------------------------------------------------------------------------------------------

--Q3. Find the Average Transaction Value

select * from phonepe

select round(avg(amount),2) as Avg_Transaction_Value
from phonepe

---------------------------------------------------------------------------------------------------

--Q4.Find the Total Cashback Given?

select * from phonepe

select round(sum(cashback),2) as Total_Cashback
from phonepe

---------------------------------------------------------------------------------------------------

--Q5. Find the Total Registered Users?

select * from phonepe

select sum(Registered_Users) as Total_users
from phonepe

---------------------------------------------------------------------------------------------------

--Q6. Find Top 5 States by Revenue?

select * from phonepe

select top 5 [state], round(sum(amount),2) as revenue
from phonepe
group by [state]
order by revenue desc

---------------------------------------------------------------------------------------------------

--Q7. Find Monthly Revenue Trend?

select * from phonepe

select 
datename(month,transaction_date) as [month],
round(sum(amount),2) as Revenue
from phonepe
group by
datename(month,transaction_date)
order by Revenue desc

---------------------------------------------------------------------------------------------------

--Q7. Find Monthly Transaction Trend?

select * from phonepe

select 
datename(month,transaction_date) as [month],
count(transaction_id) as Total_Transactions
from phonepe
group by
datename(month,transaction_date)
order by Total_Transactions desc

---------------------------------------------------------------------------------------------------

--Q8. Most Used Transaction Type?

select * from phonepe

select Transaction_type, 
count(Transaction_id) as total_Transaction
from phonepe
group by Transaction_type
order by total_Transaction desc

---------------------------------------------------------------------------------------------------

--Q9. Find Average Transaction Value by Payment Method?

select * from phonepe

select Payment_Method,
round(avg(amount),0) as Avg_Trans_Value
from phonepe
group by Payment_Method
order by Avg_Trans_Value desc

---------------------------------------------------------------------------------------------------

--Q10. Find Total Revenue Generated by Each Bank?

select * from phonepe

select Bank_name,
round(sum(amount),2) as Total_Revenue
from phonepe
group by Bank_name
order by Total_Revenue desc

---------------------------------------------------------------------------------------------------

--Q11.Find the Total no of transactions are Successed,Failed and Pending?

select * from phonepe

select transaction_status,
count(transaction_id) as Total_number
from phonepe
group by transaction_status
order by Total_number desc


--Q12. Find Failed Transactions Count State-wise

select * from phonepe

select [state],transaction_status,count(transaction_id) as Trans_not_done
from phonepe
where transaction_status <>'Success'
group by [state],transaction_status
order by [state],Trans_not_done desc

--or Total no of transactions are not done

select [state],count(transaction_id) as Trans_not_done
from phonepe
where transaction_status <>'Success'
group by [state],transaction_status
order by Trans_not_done desc

---------------------------------------------------------------------------------------------------

--Q13. Find Top Merchant Categories by transactions?

select * from phonepe

select merchant_category,
count(transaction_id) as Number_of_transaction
from phonepe
group by merchant_category
order by Number_of_transaction desc

---------------------------------------------------------------------------------------------------

--Q14.Find Revenue Contribution by Gender?

select * from phonepe

select gender,
round(sum(amount),2) as total_revenue
from phonepe
group by gender
order by total_revenue desc

---------------------------------------------------------------------------------------------------

--Q15. Which regions have low adoption but high engagement?

select * from phonepe

select [state],
sum(app_opens) as Total_App_Opens,
sum(registered_users) as Total_Registered_Users,
count(transaction_id) as Total_Transactions,
round(cast(sum(app_opens) as float)/ count(transaction_id),2) as Engagement_Ratio
from phonepe
group by [state]
order by Engagement_Ratio desc




